export const quotes = [
  "A house divided against itself cannot stand.",
  "Important principles may, and must, be inflexible.",
  "I destroy my enemies when I make them my friends.",
  "You have to do your own growing no matter how tall your grandfather was.",
  "Most people are about as happy as they make up their minds to be",
  "Most folks are about as happy as they make up their minds to be.",
  "As our case is new, we must think and act anew.",
  "Be sure you put your feet in the right place, then stand firm.",
  "I walk slowly, but I never walk backward.",
  "Truth is generally the best vindication against slander.",
  "Most folks are as happy as they make up their minds to be.",
  "I will prepare and some day my chance will come.",
  "What is necessary to change a person is to change his awareness of himself.",
  "No act of kindness, no matter how small, is ever wasted.",
  "Autumn is a second spring when every leaf is a flower.",
  "God always takes the simplest way.",
  "Learn from yesterday, live for today, hope for tomorrow.",
  "The only real valuable thing is intuition.",
  "Once we accept our limits, we go beyond them.",
  "Life is like riding a bicycle. To keep your balance you must keep moving.",
  "Feeling and longing are the motive forces behind all human endeavor and human creations.",
  "When the solution is simple, God is answering.",
  "A man should look for what is, and not for what he thinks should be.",
  "Reality is merely an illusion, albeit a very persistent one.",
  "Peace cannot be kept by force. It can only be achieved by understanding.",
  "We cannot solve our problems with the same thinking we used when we created them.",
  "If you can't explain it simply, you don't understand it well enough.",
  "Imagination is everything. It is the preview of life's coming attractions.",
  "The true sign of intelligence is not knowledge but imagination.",
  "In the middle of every difficulty lies opportunity.",
  "Logic will get you from A to B. Imagination will take you everywhere.",
  "Great ideas often receive violent opposition from mediocre minds.",
  "One may say the eternal mystery of the world is its comprehensibility.",
  "A person who never made a mistake never tried anything new.",
  "I have no special talent. I am only passionately curious.",
  "Winners have simply formed the habit of doing things losers don't like to do.",
  "Do something wonderful, people may imitate it.",
  "We should all be thankful for those people who rekindle the inner spirit.",
  "Wherever a man turns he can find someone who needs him.",
  "Do good by stealth, and blush to find it fame.",
  "Blessed is the man who expects nothing, for he shall never be disappointed.",
  "There is nothing impossible to him who will try.",
  "Trust only movement. Life happens at the level of events, not of words. Trust movement.",
  "Saying thank you is more than good manners. It is good spirituality.",
  "No person is your friend who demands your silence, or denies your right to grow.",
  "From little acorns mighty oaks do grow.",
  "Life shrinks or expands in proportion to one's courage.",
  "The personal life deeply lived always expands into truths beyond itself.",
  "To accomplish great things, we must dream as well as act.",
  "It is better to understand a little than to misunderstand a lot.",
  "The most decisive actions of our life... are most often unconsidered actions.",
  "If you smile when no one else is around, you really mean it.",
  "They say that time changes things, but you actually have to change them yourself.",
  "To follow, without halt, one aim: There is the secret of success.",
  "No one has ever become poor by giving.",
  "Joy is the best makeup.",
  "Life is a process. We are a process. The universe is a process.",
  "Trusting our intuition often saves us from disaster.",
  "How we spend our days is, of course, how we spend our lives.",
  "Listen to your intuition. It will tell you everything you need to know.",
  "I know but one freedom and that is the freedom of the mind.",
  "Discover the great ideas that lie inside you by discovering the power of sleep.",
  "Your ability to learn faster than your competition is your only sustainable competitive advantage.",
  "Well begun is half done.",
  "Change in all things is sweet.",
  "Happiness depends upon ourselves.",
  "In all things of nature there is something of the marvellous.",
  "Those that know, do. Those that understand, teach.",
  "Criticism is something you can easily avoid by saying nothing, doing nothing, and being nothing.",
  "The energy of the mind is the essence of life.",
  "If one way be better than another, that you may be sure is natures way.",
  "Mediocrity knows nothing higher than itself, but talent instantly recognizes genius.",
  "The world is a book, and those who do not travel read only a page.",
  "Yesterdays home runs don't win today's games.",
  "Without courage, wisdom bears no fruit.",
  "We cannot hold a torch to light another's path without brightening our own.",
  "The secret of success is constancy to purpose.",
  "Action may not always bring happiness; but there is no happiness without action.",
  "Through perseverance many people win success out of what seemed destined to be certain failure.",
  "Never apologize for showing feelings. When you do so, you apologize for the truth.",
  "Ignorance never settle a question.",
  "Action may not always bring happiness, but there is no happiness without action.",
  "Never apologize for showing feeling. When you do so, you apologize for truth.",
  "We make our own fortunes and we call them fate.",
  "Well done is better than well said.",
  "One today is worth two tomorrows.",
  "There never was a good knife made of bad steel.",
  "Watch the little things; a small leak will sink a great ship.",
  "Experience keeps a dear school, but fools will learn in no other.",
  "Trust yourself. You know more than you think you do.",
  "Yesterday I dared to struggle. Today I dare to win.",
  "It is easier to live through someone else than to become complete yourself.",
  "Success is a lousy teacher. It seduces smart people into thinking they can't lose.",
  "Our passion is our strength.",
  "We must not allow ourselves to become like the system we oppose.",
  "The heart has its reasons which reason knows not of.",
  "Kind words do not cost much. Yet they accomplish much.",
  "We are all something, but none of us are everything.",
  "We know the truth, not only by the reason, but by the heart.",
  "We must learn our limits. We are all something, but none of us are everything.",
  "Set your goals high, and don't stop till you get there.",
  "All I can say about life is, Oh God, enjoy it",
  "All know the way; few actually walk it.",
  "Excellence is to do a common thing in an uncommon way.",
  "No yesterdays are ever wasted for those who give themselves to today.",
  "Goals are the fuel in the furnace of achievement.",
  "Whatever we expect with confidence becomes our own self fulfilling prophecy.",
  "If you spend too much time thinking about a thing, you'll never get it done.",
  "To know oneself is to study oneself in action with another person.",
  "As you think, so shall you become.",
  "Mistakes are always forgivable, if one has the courage to admit them.",
  "The less effort, the faster and more powerful you will be.",
  "To hell with circumstances; I create opportunities.",
  "Knowing is not enough, we must apply. Willing is not enough, we must do.",
  "Be happy, but never satisfied.",
  "There is nothing in a caterpillar that tells you it's going to be a butterfly.",
  "Peace comes from within. Do not seek it without.",
  "Work out your own salvation. Do not depend on others.",
  "He is able who thinks he is able.",
  "Those who are free of resentful thoughts surely find peace.",
  "What we think, we become.",
  "It is better to travel well than to arrive.",
  "The mind is everything. What you think you become.",
  "In separateness lies the world's great misery, in compassion lies the world's true strength.",
  "Happiness comes when your work and words are of benefit to yourself and others.",
  "Just as a candle cannot burn without fire, men cannot live without a spiritual life.",
  "If you light a lamp for somebody, it will also brighten your path.",
  "Your worst enemy cannot harm you as much as your own unguarded thoughts.",
  "The way is not in the sky. The way is in the heart.",
  "Three things cannot be long hidden: the sun, the moon, and the truth.",
  "You, yourself, as much as anybody in the entire universe, deserve your love and affection.",
  "You will not be punished for your anger, you will be punished by your anger.",
  "The foot feels the foot when it feels the ground.",
  "Always be mindful of the kindness and not the faults of others.",
  "Better than a thousand hollow words, is one word that brings peace.",
  "A jug fills drop by drop.",
  "You only lose what you cling to.",
  "Every human being is the author of his own health or disease.",
  "Your body is precious. It is our vehicle for awakening. Treat it with care.",
  "Chaos is inherent in all compounded things. Strive on with diligence.",
  "No matter how hard the past, you can always begin again.",
  "You cannot travel the path until you have become the path itself.",
  "Remembering a wrong is like carrying a burden on the mind.",
  "Better than a thousand hollow words is one word that brings peace.",
  "Fate is in your hands and no one else's",
  "What you give is what you get.",
  "The best teacher is experience learned from failures.",
  "What you fear is that which requires action to overcome.",
  "If you cannot be silent be brilliant and thoughtful.",
  "Someone is special only if you tell them.",
  "Give thanks for the rain of life that propels us to reach new horizons.",
  "You can't trust without risk but neither can you live in a cocoon.",
  "Passion creates the desire for more and action fuelled by passion creates a future.",
  "Experience can only be gained by doing not by thinking or dreaming.",
  "It can't be spring if your heart is filled with past failures.",
  "I may not know everything, but everything is not known yet anyway.",
  "Complaining doesn't change a thing only taking action does.",
  "Spring is a time for rebirth and the fulfilment of new life.",
  "When anger use your energy to do something productive.",
  "We cannot do everything at once, but we can do something at once.",
  "I have never been hurt by anything I didn't say.",
  "A man who doesn't trust himself can never really trust anyone else.",
  "Who looks outside, dreams; who looks inside, awakes.",
  "You are what you do, not what you say you do.",
  "Everything that irritates us about others can lead us to an understanding about ourselves.",
  "Everything that irritates us about others can lead us to an understanding of ourselves.",
  "In all chaos there is a cosmos, in all disorder a secret order.",
  "Knowledge rests not upon truth alone, but upon error also.",
  "Everything that irritates us about others can lead us to a better understanding of ourselves.",
  "Nothing happens unless first we dream.",
  "Silence is deep as Eternity, Speech is shallow as Time.",
  "Being angry never solves anything.",
  "Rather than wishing for change, you first must be prepared to change.",
  "Our ability to achieve happiness and success depends on the strength of our wings.",
  "You are special, you are unique, you are the best",
  "The man who trusts men will make fewer mistakes than he who distrusts them.",
  "Those who will play with cats must expect to be scratched.",
  "Be slow of tongue and quick of eye.",
  "A man is great by deeds, not by birth.",
  "Error is discipline through which we advance.",
  "Every man is a volume if you know how to read him.",
  "Impossibilities are merely things which we have not yet learned.",
  "One fails forward toward success.",
  "The heart has eyes which the brain knows nothing of.",
  "Life is what happens to you and how you react to it.",
  "Life is so constructed that an event does not, cannot, will not, match the expectation.",
  "Sleep is the real beauty secret, but I don't get enough of that.",
  "Happiness does not come from having much, but from being attached to little.",
  "Learning is a treasure that will follow its owner everywhere",
  "Talk doesn't cook rice.",
  "Tension is who you think you should be. Relaxation is who you are.",
  "People who say it cannot be done should not interrupt those who are doing it.",
  "A gem cannot be polished without friction, nor a man perfected without trials.",
  "Example has more followers than reason.",
  "Once you choose hope, anythings possible.",
  "When deeds and words are in accord, the whole world is transformed.",
  "We must not say every mistake is a foolish one.",
  "Gratitude is not only the greatest of virtues, but the parent of all the others.",
  "The one who always loses, is the only person who gets the reward.",
  "There are people who have money and people who are rich.",
  "Study the past, if you would divine the future.",
  "Silence is a true friend who never betrays.",
  "Think of tomorrow, the past can't be mended.",
  "Wherever you go, go with all your heart.",
  "The more you know yourself, the more you forgive yourself.",
  "To be wrong is nothing unless you continue to remember it.",
  "The cautious seldom err.",
  "What you do not want done to yourself, do not do to others.",
  "Reviewing what you have learned and learning anew, you are fit to be a teacher.",
  "The superior man is satisfied and composed; the mean man is always full of distress.",
  "It does not matter how slowly you go as long as you do not stop.",
  "To study and not think is a waste. To think and not study is dangerous.",
  "The superior man is modest in his speech, but exceeds in his actions.",
  "Silence is the true friend that never betrays.",
  "To be wronged is nothing unless you continue to remember it.",
  "They must often change, who would be constant in happiness or wisdom.",
  "Everything has beauty, but not everyone sees it.",
  "I want you to be everything that's you, deep at the center of your being.",
  "The Superior Man is aware of Righteousness, the inferior man is aware of advantage.",
  "Fine words and an insinuating appearance are seldom associated with true virtue",
  "Our greatest glory is not in never falling, but in rising every time we fall.",
  "I hear and I forget. I see and I remember. I do and I understand.",
  "Ability will never catch up with the demand for it.",
  "The superior man acts before he speaks, and afterwards speaks according to his action.",
  "Learning without reflection is a waste, reflection without learning is dangerous.",
  "Sincerity is the way of Heaven. The attainment of sincerity is the way of men.",
  "He who wishes to secure the good of others, has already secured his own.",
  "Life is really simple, but we insist on making it complicated.",
  "Life is a succession of moments. To live each one is to succeed.",
  "When performance exceeds ambition, the overlap is called success.",
  "To want to be what one can be is purpose in life.",
  "Genuine sincerity opens people's hearts, while manipulation causes them to close.",
  "Be kind whenever possible. It is always possible.",
  "Sleep is the best meditation.",
  "I believe that we are fundamentally the same and have the same basic potential.",
  "Love and compassion open our own inner life, reducing stress, distrust and loneliness.",
  "More often than not, anger is actually an indication of weakness rather than of strength.",
  "Happiness is not something ready made. It comes from your own actions.",
  "Remember that sometimes not getting what you want is a wonderful stroke of luck.",
  "Happiness mainly comes from our own attitude, rather than from external factors.",
  "Compassion and happiness are not a sign of weakness but a sign of strength.",
  "See the positive side, the potential, and make an effort.",
  "When fate hands us a lemon, let's try to make lemonade.",
  "Success is getting what you want. Happiness is wanting what you get.",
  "It's important to know that words don't move mountains. Work, exacting work moves mountains.",
  "The secret to a rich life is to have more beginnings than endings.",
  "Be here now. Be someplace else later. Is that so complicated",
  "Tomorrow belongs to those who can hear it coming",
  "No day in which you learn something is a complete loss.",
  "Real success is finding your lifework in the work that you love.",
  "When you make a choice, you change the future.",
  "Small opportunities are often the beginning of great enterprises.",
  "You must welcome change as the rule but not as your ruler.",
  "The only person who never makes mistakes is the person who never does anything.",
  "The desire to create is one of the deepest yearnings of the human soul.",
  "The art of being a slave is to rule one's master.",
  "A man of ability and the desire to accomplish something can do anything.",
  "Everything in life is luck.",
  "You have to think anyway, so why not think big",
  "Sometimes by losing a battle you find a new way to win the war.",
  "Gratitude is riches. Complaint is poverty.",
  "Fear grows in darkness; if you think there's a bogeyman around, turn on the light.",
  "Only when we are no longer afraid do we begin to live.",
  "Be your own hero, it's cheaper than a movie ticket.",
  "Don't cry because it's over. Smile because it happened.",
  "It takes courage to grow up and become who you really are.",
  "It is not uncommon for people to spend their whole life waiting to start living.",
  "Whenever something negative happens to you, there is a deep lesson concealed within it.",
  "The universe is full of magical things, patiently waiting for our wits to grow sharper.",
  "The inner fire is the most important thing mankind possesses.",
  "If only we'd stop trying to be happy we'd have a pretty good time.",
  "A man is not old as long as he is seeking something.",
  "The winds and waves are always on the side of the ablest navigators.",
  "On every thorn, delightful wisdom grows, In every rill a sweet instruction flows.",
  "Every action of our lives touches on some chord that will vibrate in eternity.",
  "We have committed the Golden Rule to memory; let us now commit it to life.",
  "There is no failure except in no longer trying.",
  "To avoid criticism, do nothing, say nothing, be nothing.",
  "The final proof of greatness lies in being able to endure criticism without resentment.",
  "No one can make you feel inferior without your consent.",
  "Do one thing every day that scares you.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "I think somehow we learn who we really are and then live with that decision.",
  "It is not fair to ask of others what you are unwilling to do yourself.",
  "You must do the things you think you cannot do.",
  "Light tomorrow with today",
  "Love doesn't make the world go round, love is what makes the ride worthwhile.",
  "Who so loves, believes the impossible.",
  "He who angers you conquers you.",
  "It isn't where you come from, it's where you're going that counts.",
  "The truest greatness lies in being kind, the truest wisdom in a happy mind.",
  "Bite off more than you can chew, then chew it.",
  "Don't ruin the present with the ruined past.",
  "The cure for boredom is curiosity. There is no cure for curiosity.",
  "Take heed: you do not find what you do not seek.",
  "Freedom is the right to live as we wish.",
  "Difficulties are things that show a person what they are.",
  "If you wish to be a writer, write.",
  "Practice yourself, for heavens sake in little things, and then proceed to greater.",
  "Know, first, who you are, and then adorn yourself accordingly.",
  "Men are disturbed not by things, but by the view which they take of them.",
  "No man is free who is not master of himself.",
  "It's not what happens to you, but how you react to it that matters.",
  "The world turns aside to let any man pass who knows where he is going.",
  "Keep silence for the most part, and speak only when you must, and then briefly.",
  "It is impossible for a man to learn what he thinks he already knows.",
  "The greatest barrier to success is the fear of failure.",
  "Never mistake motion for action.",
  "The wisest men follow their own direction.",
  "The truth which has made us free will in the end make us glad also.",
  "The doors we open and close each day decide the lives we live.",
  "I attribute my success to this: I never gave or took an excuse.",
  "Do what you can. Want what you have. Be who you are.",
  "As we risk ourselves, we grow. Each new experience is a risk.",
  "Nothing is so strong as gentleness. Nothing is so gentle as real strength.",
  "A prudent question is one half of wisdom.",
  "A wise man will make more opportunities than he finds.",
  "The beginning of knowledge is the discovery of something we do not understand.",
  "Your future depends on many things, but mostly on you.",
  "Learn to listen. Opportunity could be knocking at your door very softly.",
  "Be a good listener. Your ears will never get you in trouble.",
  "Respect should be earned by actions, and not acquired by years.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "When you come to the end of your rope, tie a knot and hang on.",
  "Beware of missing chances; otherwise it may be altogether too late some day.",
  "If there is no struggle, there is no progress.",
  "Progress always involves risks. You can't steal second base and keep your foot on first.",
  "Keep true to the dreams of thy youth.",
  "The soul is healed by being with children.",
  "To be tested is good. The challenged life may be the best therapist.",
  "It is fatal to enter any war without the will to win it.",
  "Prosperity depends more on wanting what you have than having what you want.",
  "We don't stop playing because we grow old; we grow old because we stop playing.",
  "Life isn't about finding yourself. Life is about creating yourself.",
  "The possibilities are numerous once we decide to act and not react.",
  "It is never too late to be what you might have been.",
  "Each day can be one of triumph if you keep up your interests.",
  "Myths which are believed in tend to become true.",
  "If a man does his best, what else is there",
  "Accept challenges, so that you may feel the exhilaration of victory.",
  "There is only one happiness in life, to love and be loved.",
  "Those who cannot learn from history are doomed to repeat it.",
  "My reputation grows with every failure.",
  "Silence is a fence around wisdom.",
  "Begin to weave and God will give you the thread.",
  "If the shoe doesn't fit, must we change the foot",
  "A man sees in the world what he carries in his heart.",
  "What is not started today is never finished tomorrow.",
  "Just trust yourself, then you will know how to live.",
  "Our kindness may be the most persuasive argument for that which we believe.",
  "Life is what you make of it. Always has been, always will be.",
  "Reality does not conform to the ideal, but confirms it.",
  "Don't be afraid to go out on a limb. That's where the fruit is.",
  "The worst bankrupt in the world is the person who has lost his enthusiasm.",
  "What worries you masters you.",
  "It is not so important to know everything as to appreciate what we learn.",
  "Obstacles are those things you see when you take your eyes off the goal.",
  "We are all inclined to judge ourselves by our ideals; others, by their acts.",
  "All serious daring starts from within.",
  "For success, attitude is equally as important as ability.",
  "Give thanks for a little and you will find a lot.",
  "It is on our failures that we base a new and different and better success.",
  "Absence makes the heart grow fonder.",
  "Keep yourself to the sunshine and you cannot see the shadow.",
  "Never bend your head. Always hold it high. Look the world right in the eye.",
  "Almost everything comes from nothing.",
  "The eye sees only what the mind is prepared to comprehend.",
  "Think like a man of action; act like a man of thought.",
  "So long as a person is capable of self renewal they are a living being.",
  "Gratitude is the fairest blossom which springs from the soul.",
  "I cannot make my days longer so I strive to make them better.",
  "The price of anything is the amount of life you exchange for it.",
  "If you think you can, you can. And if you think you can't, you're right.",
  "Quality means doing it right when no one is looking.",
  "Obstacles are those frightful things you see when you take your eyes off your goal.",
  "Trouble is only opportunity in work clothes.",
  "Things do not change, we change.",
  "The world is but a canvas to the imagination.",
  "Things do not change; we change.",
  "All is flux; nothing stays still.",
  "You cannot step twice into the same river, for other waters are continually flowing in.",
  "If I know what love is, it is because of you.",
  "When you doubt your power, you give power to your doubt.",
  "Begin, be bold, and venture to be wise.",
  "All seasons are beautiful for the person who carries happiness within.",
  "Problems are only opportunities with thorns on them.",
  "Science is organized knowledge. Wisdom is organized life.",
  "You can't shake hands with a clenched fist.",
  "We can only learn to love by loving.",
  "The noblest worship is to make yourself as good and as just as you can.",
  "Good timber does not grow with ease; the stronger the wind, the stronger the trees.",
  "Rock bottom became the solid foundation on which I rebuilt my life.",
  "Everything you want is on the other side of fear.",
  "A weed is no more than a flower in disguise.",
  "The foolish man seeks happiness in the distance; the wise grows it under his feet.",
  "The foolish man seeks happiness in the distance, the wise grows it under his feet.",
  "Success is determined by those whom prove the impossible, possible.",
  "The most successful people are those who are good at plan B.",
  "By accepting yourself and being fully what you are, your presence can make others happy.",
  "Don't compromise yourself. You are all you've got.",
  "The day you decide to do it is your lucky day.",
  "Vision without action is a daydream. Action without vision is a nightmare.",
  "No is easier to do. Yes is easier to say.",
  "Sadness flies away on the wings of time.",
  "Freedom is what you do with what's been done to you.",
  "Before you put on a frown, make absolutely sure there are no smiles available.",
  "Either you run the day or the day runs you.",
  "Give whatever you are doing and whoever you are with the gift of your attention.",
  "The more you care, the stronger you can be.",
  "If you aren't going all the way, why go at all",
  "Believe deep down in your heart that you're destined to do great things.",
  "Difficulties increase the nearer we get to the goal.",
  "Great talent finds happiness in execution.",
  "Character develops itself in the stream of life.",
  "A really great talent finds its happiness in execution.",
  "Mountains cannot be surmounted except by winding paths.",
  "Knowing is not enough; we must apply",
  "In the end we retain from our studies only that which we practically apply.",
  "Correction does much, but encouragement does more.",
  "Kindness is the golden chain by which society is bound together.",
  "You cannot have what you do not want.",
  "Happiness often sneaks in through a door you didn't know you left open.",
  "The bird of paradise alights only upon the hand that does not grasp.",
  "Slow down and everything you are chasing will come around and catch you.",
  "Without some goals and some efforts to reach it, no man can live.",
  "Arriving at one point is the starting point to another.",
  "Every great advance in science has issued from a new audacity of the imagination.",
  "Fortune befriends the bold.",
  "A thing well said will be wit in all languages.",
  "All the great performers I have worked with are fuelled by a personal dream.",
  "An ounce of emotion is equal to a ton of facts.",
  "Love is the flower you've got to let grow.",
  "Reality leaves a lot to the imagination.",
  "Time you enjoy wasting, was not wasted.",
  "Yeah we all shine on, like the moon, and the stars, and the sun.",
  "Life is what happens while you are making other plans.",
  "Time you enjoyed wasting was not wasted.",
  "Life is what happens to you while you're busy making other plans.",
  "I have always thought the actions of men the best interpreters of their thoughts.",
  "A day of worry is more exhausting than a day of work.",
  "What we see depends mainly on what we look for.",
  "Not what we have but what we enjoy constitutes our abundance.",
  "Life is movement we breathe, we eat, we walk, we move",
  "The only real mistake is the one from which we learn nothing.",
  "Quality is never an accident; it is always the result of intelligent effort.",
  "Dreams come true. Without that possibility, nature would not incite us to have them.",
  "Never mistake activity for achievement.",
  "You can't stop the waves, but you can learn to surf.",
  "Intuition will tell the thinking mind where to look next.",
  "Pick battles big enough to matter, small enough to win.",
  "Discovery consists of seeing what everybody has seen and thinking what nobody else has thought.",
  "Your sacred space is where you can find yourself again and again.",
  "To live a creative life, we must lose our fear of being wrong.",
  "He who has imagination without learning has wings but no feet.",
  "I believe in one thing only, the power of human will.",
  "Trust your hunches. They're usually based on facts filed away just below the conscious level.",
  "It is through science that we prove, but through intuition that we discover.",
  "Be what you are. This is the first step toward becoming better than you are.",
  "A little knowledge that acts is worth infinitely more than much knowledge that is idle.",
  "Beauty is not in the face; beauty is a light in the heart.",
  "We choose our joys and sorrows long before we experience them.",
  "Be like the flower, turn your face to the sun.",
  "Life is change. Growth is optional. Choose wisely.",
  "If you're not prepared to be wrong, you'll never come up with anything original.",
  "To be upset over what you don't have is to waste what you do have.",
  "We must embrace pain and burn it as fuel for our journey.",
  "We learn what we have said from those who listen to our speaking.",
  "You won't skid if you stay in a rut.",
  "If you kick a stone in anger, you'll hurt your own foot.",
  "Be gentle first with yourself if you wish to be gentle with others.",
  "Be the chief but never the lord.",
  "To lead people walk behind them.",
  "Doing nothing is better than being busy doing nothing.",
  "Anticipate the difficult by managing the easy.",
  "He who talks more is sooner exhausted.",
  "He who is contented is rich.",
  "The journey of a thousand miles begins with one step.",
  "An ant on the move does more than a dozing ox",
  "If you correct your mind, the rest of your life will fall into place.",
  "If you would take, you must first give, this is the beginning of intelligence.",
  "When you realize there is nothing lacking, the whole world belongs to you.",
  "He who conquers others is strong; He who conquers himself is mighty.",
  "He who obtains has little. He who scatters has much.",
  "Silence is a source of great strength.",
  "If you do not change direction, you may end up where you are heading.",
  "From wonder into wonder existence opens.",
  "He who knows himself is enlightened.",
  "Great acts are made up of small deeds.",
  "Nothing is softer or more flexible than water, yet nothing can resist it.",
  "When I let go of what I am, I become what I might be.",
  "To see things in the seed, that is genius.",
  "The key to growth is the introduction of higher dimensions of consciousness into our awareness.",
  "He who knows, does not speak. He who speaks, does not know.",
  "He who knows others is wise. He who knows himself is enlightened.",
  "One who is too insistent on his own views, finds few to agree with him.",
  "He who knows that enough is enough will always have enough.",
  "Music in the soul can be heard by the universe.",
  "A goal without a plan is just a wish.",
  "Imagination is the highest kite one can fly.",
  "Sometimes the biggest act of courage is a small one.",
  "If you don't know where you are going, you will probably end up somewhere else.",
  "Great is the art of beginning, but greater is the art of ending.",
  "People seldom notice old clothes if you wear a big smile.",
  "Always be smarter than the people who hire you.",
  "Never idealize others. They will never live up to your expectations.",
  "Don't smother each other. No one can grow in the shade.",
  "The two most powerful warriors are patience and time.",
  "Everyone thinks of changing the world, but no one thinks of changing himself.",
  "We lost because we told ourselves we lost.",
  "Who sows virtue reaps honour.",
  "All our knowledge has its origins in our perceptions.",
  "Nothing strengthens authority so much as silence.",
  "He who is fixed to a star does not change his mind.",
  "Time stays long enough for anyone who will use it.",
  "Shoot for the moon. Even if you miss, you'll land among the stars.",
  "To forgive is to set a prisoner free and realize that prisoner was you.",
  "People may doubt what you say, but they will believe what you do.",
  "Nobody will believe in you unless you believe in yourself.",
  "I always wanted to be somebody, but I should have been more specific.",
  "I have done my best: that is about all the philosophy of living one needs.",
  "The shortest answer is doing.",
  "I can't believe that God put us on this earth to be ordinary.",
  "Chance favors the prepared mind.",
  "I'm not afraid of storms, for I'm learning how to sail my ship.",
  "Blaze with the fire that is never extinguished.",
  "Your outlook on life is a direct reflection on how much you like yourself.",
  "Society develops wit, but its contemplation alone forms genius.",
  "We must become the change we want to see.",
  "The future depends on what you do today.",
  "Strength does not come from physical capacity. It comes from an indomitable will.",
  "It is the quality of our work which will please God, not the quantity.",
  "The odds of hitting your target go up dramatically when you aim at it.",
  "It has never been my object to record my dreams, just to realize them.",
  "I allow my intuition to lead my path.",
  "Turn your face toward the sun and the shadows will fall behind you.",
  "Each day provides its own gifts.",
  "Loss is nothing else but change,and change is Natures delight.",
  "He who lives in harmony with himself lives in harmony with the universe.",
  "The universe is transformation; our life is what our thoughts make it.",
  "Everything that exists is in a manner the seed of that which will be.",
  "He who lives in harmony with himself lives in harmony with the world.",
  "Waste no more time arguing about what a good man should be. Be one.",
  "It is only possible to live happily ever after on a day to day basis.",
  "If you have knowledge, let others light their candles in it.",
  "Self complacency is fatal to progress.",
  "You really can change the world if you care enough.",
  "I never see what has been done; I only see what remains to be done.",
  "Nothing in life is to be feared. It is only to be understood.",
  "Be less curious about people and more curious about ideas.",
  "A thing long expected takes the form of the unexpected when at last it comes.",
  "Always tell the truth. That way, you don't have to remember what you said.",
  "When in doubt, tell the truth.",
  "Whoever is happy will make others happy, too.",
  "The exercise of an extraordinary gift is the supremest pleasure in life.",
  "Kindness is the language which the deaf can hear and the blind can see.",
  "Wrinkles should merely indicate where smiles have been.",
  "To get the full value of joy you must have someone to divide it with.",
  "Wicked people are always surprised to find ability in those that are good.",
  "Stay away from what might have been and look at what will be.",
  "The greatest part of our happiness depends on our dispositions, not our circumstances.",
  "Knowledge is a process of piling up facts; wisdom lies in their simplification.",
  "Remove Christ from the Scriptures and there is nothing left.",
  "Love is the only force capable of transforming an enemy into friend.",
  "Who we are never changes. Who we think we are does.",
  "Without faith, nothing is possible. With it, nothing is impossible.",
  "You block your dream when you allow your fear to grow bigger than your faith.",
  "The beginning is always today.",
  "I believe that every person is born with talent.",
  "If you don't like something, change it. If you can't change it, change your attitude.",
  "If one is lucky, a solitary fantasy can totally transform one million realities.",
  "When you learn, teach. When you get, give.",
  "All great achievements require time.",
  "We may encounter many defeats but we must not be defeated.",
  "Nothing will work unless you do.",
  "You can't use up creativity. The more you use, the more you have.",
  "To fly, we have to have resistance.",
  "To succeed, we must first believe that we can.",
  "Life is not measured by the breaths you take, but by its breathtaking moments.",
  "Faith in oneself is the best and safest course.",
  "There is no greater harm than that of time wasted.",
  "You're never a loser until you quit trying.",
  "The weak can never forgive. Forgiveness is the attribute of the strong.",
  "Freedom is not worth having if it does not connote freedom to err.",
  "Forgiveness is choosing to love. It is the first skill of self giving love.",
  "Be the change that you want to see in the world.",
  "The best thing in every noble dream is the dreamer...",
  "If you spend your whole life waiting for the storm, you'll never enjoy the sunshine.",
  "Be faithful in small things because it is in them that your strength lies.",
  "We shall never know all the good that a simple smile can do.",
  "If you can't feed a hundred people, then feed just one.",
  "Peace begins with a smile.",
  "Kind words can be short and easy to speak but their echoes are truly endless.",
  "We can do no great things, only small things with great love.",
  "Do not wait for leaders; do it alone, person to person.",
  "Kind words can be short and easy to speak, but their echoes are truly endless.",
  "The universe is made of stories, not atoms.",
  "Think how hard physics would be if particles could think.",
  "It is impossible to feel grateful and depressed in the same moment.",
  "Victory belongs to the most persevering.",
  "The truest wisdom is a resolute determination.",
  "Imagination rules the world.",
  "He who fears being conquered is sure of defeat.",
  "If you want a thing done well, do it yourself.",
  "The best cure for the body is a quiet mind.",
  "Ideas are the beginning points of all fortunes.",
  "Don't wait. The time will never be just right.",
  "You give before you get.",
  "A goal is a dream with a deadline.",
  "You can do it if you believe you can",
  "No alibi will save you from accepting the responsibility.",
  "Happiness is found in doing, not merely possessing.",
  "Fears are nothing more than a state of mind.",
  "Most great people have attained their greatest success just one step beyond their greatest failure.",
  "When your desires are strong enough you will appear to possess superhuman powers to achieve.",
  "No man can succeed in a line of endeavor which he does not like.",
  "If you cannot do great things, do small things in a great way.",
  "All achievements, all earned riches, have their beginning in an idea.",
  "You might well remember that nothing can bring you success but yourself.",
  "Your big opportunity may be right where you are now.",
  "Opportunity often comes disguised in the form of misfortune, or temporary defeat.",
  "The ladder of success is never crowded at the top.",
  "There are no limitations to the mind except those we acknowledge.",
  "As we are liberated from our own fear, our presence automatically liberates others.",
  "You need chaos in your soul to give birth to a dancing star.",
  "By believing passionately in something that does not yet exist, we create it.",
  "Never deny a diagnosis, but do deny the negative verdict that may go with it.",
  "If you want things to be different, perhaps the answer is to become different yourself.",
  "Each misfortune you encounter will carry in it the seed of tomorrows good luck.",
  "Always do your best. What you plant now, you will harvest later.",
  "Always seek out the seed of triumph in every adversity.",
  "Failure will never overtake me if my determination to succeed is strong enough.",
  "Love is the master key that opens the gates of happiness.",
  "Fame usually comes to those who are thinking about something else.",
  "Follow your instincts. That is where true wisdom manifests itself.",
  "I don't believe in failure. It is not failure if you enjoyed the process.",
  "The biggest adventure you can ever take is to live the life of your dreams.",
  "I don't believe in failure. It's not failure if you enjoyed the process.",
  "Don't settle for a relationship that won't let you be yourself.",
  "All men who have achieved great things have been great dreamers.",
  "Experience is simply the name we give our mistakes.",
  "The smallest act of kindness is worth more than the grandest intention.",
  "Anybody can make history. Only a great man can write it.",
  "Be yourself; everyone else is already taken.",
  "The cause is hidden. The effect is visible to all.",
  "All things change; nothing perishes.",
  "Take rest; a field that has rested gives a bountiful crop.",
  "Everything you can imagine is real.",
  "Inspiration exists, but it has to find us working.",
  "Action is the foundational key to all success.",
  "I begin with an idea and then it becomes something else.",
  "Forgiveness does not change the past, but it does enlarge the future.",
  "The awareness of our own strength makes us modest.",
  "Decision is a risk rooted in the courage of being free.",
  "Write your plans in pencil and give God the eraser.",
  "One faces the future with ones past.",
  "Growth itself contains the germ of happiness.",
  "The truth is always exciting. Speak it, then. Life is dull without it.",
  "The truth you believe and cling to makes you unavailable to hear anything new.",
  "Nothing ever goes away until it has taught us what we need to know.",
  "The greatest obstacle to connecting with our joy is resentment.",
  "The future is completely open, and we are writing it moment to moment.",
  "Fear not for the future, weep not for the past.",
  "Time is the wisest counsellor of all.",
  "Efficiency is doing things right; effectiveness is doing the right things.",
  "You cannot predict the future, but you can create it.",
  "Until we can manage time, we can manage nothing else.",
  "Meaning is not what you start with but what you end up with.",
  "Moments of complete apathy are the best for new creations.",
  "Either I will find a way, or I will make one.",
  "The pain passes, but the beauty remains.",
  "A good decision is based on knowledge and not on numbers.",
  "Good actions give strength to ourselves and inspire good actions in others.",
  "What we achieve inwardly will change outer reality.",
  "Know how to listen, and you will profit even from those who talk badly.",
  "Only do what your heart tells you.",
  "A rolling stone gathers no moss.",
  "While we stop to think, we often miss our opportunity.",
  "Better be ignorant of a matter than half know it.",
  "I have often regretted my speech, never my silence.",
  "Do not turn back when you are just at the goal.",
  "Never promise more than you can perform.",
  "We read the world wrong and say that it deceives us.",
  "You don't play for revenge. You play for respect and pride",
  "Let everything happen to you. Beauty and terror. Just keep going. No feeling is final",
  "Skill to do comes of doing.",
  "The years teach much which the days never know.",
  "Our distrust is very expensive.",
  "Good luck is another name for tenacity of purpose.",
  "Life is a progress, and not a station.",
  "The world makes way for the man who knows where he is going.",
  "Life is a succession of lessons, which must be lived to be understood.",
  "Self trust is the first secret of success.",
  "Go put your creed into the deed. Nor speak with double tongue.",
  "We aim above the mark to hit the mark.",
  "Nature is a mutable cloud which is always and never the same.",
  "Build a better mousetrap and the world will beat a path to your door.",
  "Nothing is at last sacred but the integrity of your own mind.",
  "Nothing great was ever achieved without enthusiasm.",
  "Truth, and goodness, and beauty are but different faces of the same all.",
  "To be great is to be misunderstood.",
  "Make the most of yourself, for that is all there is of you.",
  "Everything in the universe goes by indirection. There are no straight lines.",
  "Make the most of yourself for that is all there is of you.",
  "Thought is the blossom; language the bud; action the fruit behind it.",
  "What is a weed A plant whose virtues have not yet been discovered.",
  "Belief consists in accepting the affirmations of the soul; Unbelief, in denying them.",
  "Good thoughts are no better than good dreams, unless they be executed.",
  "In skating over thin ice our safety is in our speed.",
  "So is cheerfulness, or a good temper, the more it is spent, the more remains.",
  "Bad times have a scientific value. These are occasions a good learner would not miss.",
  "The only way to have a friend is to be one.",
  "Excellence is not a skill. It is an attitude.",
  "Our strength grows out of our weaknesses.",
  "It is only when the mind and character slumber that the dress can be seen.",
  "Imagination is not a talent of some men but is the health of every man.",
  "Most of the shadows of life are caused by standing in our own sunshine.",
  "Divide each difficulty into as many parts as is feasible and necessary to resolve it.",
  "Argue for your limitations, and sure enough they're yours.",
  "In order to win, you must expect to win.",
  "The simplest things are often the truest.",
  "To bring anything into your life, imagine that it's already there.",
  "Strong beliefs win strong men, and then make them stronger.",
  "Every problem has a gift for you in its hands.",
  "The best way to pay for a lovely moment is to enjoy it.",
  "Sooner or later, those who win are those who think they can.",
  "Happiness is the reward we get for living to the highest right we know.",
  "Every gift from a friend is a wish for your happiness.",
  "Learning is finding out what you already know.",
  "Ask yourself the secret of your success. Listen to your answer, and practice it.",
  "The meaning I picked, the one that changed my life: Overcome fear, behold wonder.",
  "Listen to what you know instead of what you fear.",
  "What the caterpillar calls the end of the world, the master calls a butterfly.",
  "You teach best what you most need to learn.",
  "The undertaking of a new action brings new strength.",
  "What I cannot create, I do not understand.",
  "Chaos and Order are not enemies, only opposites.",
  "Lose an hour in the morning, and you will spend all day looking for it.",
  "Creativity comes from trust. Trust your instincts. And never hope more than you work.",
  "The best way out is always through.",
  "In three words I can sum up everything I've learned about life: it goes on.",
  "Never ignore a gut feeling, but never believe that it's enough.",
  "Only those who dare to fail greatly can ever achieve greatly.",
  "Don't think of it as failure. Think of it as time released success.",
  "As we grow as unique persons, we learn to respect the uniqueness of others.",
  "Failure doesn't mean you are a failure it just means you haven't succeeded yet.",
  "Don't judge each day by the harvest you reap but by the seeds you plant.",
  "Nothing is a waste of time if you use the experience wisely.",
  "All perceiving is also thinking, all reasoning is also intuition, all observation is also invention.",
  "Let the beauty of what you love be what you do.",
  "Let yourself be silently drawn by the stronger pull of what you really love."
] as const;
